# Generated by Django 6.0.1 on 2026-02-12 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_play_user_storyownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('story_id', models.IntegerField(db_index=True)),
                ('current_page_id', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField(db_index=True)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField(db_index=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['resolved', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='play',
            name='ending_page_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='story_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plays', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storyownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_flask_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['story_id', 'ending_page_id'], name='stories_pla_story_i_4f5a63_idx'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['user', 'story_id'], name='stories_pla_user_id_da28a4_idx'),
        ),
        migrations.AddField(
            model_name='playsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='playsession',
            constraint=models.UniqueConstraint(fields=('session_key', 'story_id'), name='uniq_session_story_progress'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['story_id'], name='stories_rat_story_i_9bb636_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'story_id'), name='uniq_user_story_rating'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['story_id', 'resolved'], name='stories_rep_story_i_9a3297_idx'),
        ),
    ]
